CREATE TABLE dispatch_ai_settings (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    auto_schedule_enabled BIT NOT NULL DEFAULT b'0',
    auto_schedule_time VARCHAR(5) NOT NULL DEFAULT '00:05',
    default_strategy_mode VARCHAR(32) NOT NULL DEFAULT 'NEAR_TO_FAR',
    anchor_name VARCHAR(128) NOT NULL DEFAULT '五环天地',
    anchor_address VARCHAR(255) NOT NULL DEFAULT '湖北省武汉市硚口区荟聚中心',
    ai_enabled BIT NOT NULL DEFAULT b'0',
    api_base_url VARCHAR(255) NOT NULL DEFAULT 'https://api.deepseek.com',
    api_key VARCHAR(255) NOT NULL DEFAULT '',
    ai_model VARCHAR(64) NOT NULL DEFAULT 'deepseek-chat',
    ai_prompt_template TEXT NOT NULL,
    low_balance_threshold DECIMAL(10, 2) NOT NULL DEFAULT 20.00,
    balance_available BIT NOT NULL DEFAULT b'0',
    balance_currency VARCHAR(16) NOT NULL DEFAULT 'CNY',
    total_balance VARCHAR(32) NOT NULL DEFAULT '',
    granted_balance VARCHAR(32) NOT NULL DEFAULT '',
    topped_up_balance VARCHAR(32) NOT NULL DEFAULT '',
    balance_checked_at TIMESTAMP NULL,
    updated_by VARCHAR(64) NOT NULL DEFAULT 'system',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO dispatch_ai_settings (
    id,
    auto_schedule_enabled,
    auto_schedule_time,
    default_strategy_mode,
    anchor_name,
    anchor_address,
    ai_enabled,
    api_base_url,
    api_key,
    ai_model,
    ai_prompt_template,
    low_balance_threshold,
    balance_available,
    balance_currency,
    total_balance,
    granted_balance,
    topped_up_balance,
    updated_by
) VALUES (
    1,
    b'0',
    '00:05',
    'NEAR_TO_FAR',
    '五环天地',
    '湖北省武汉市硚口区荟聚中心',
    b'0',
    'https://api.deepseek.com',
    '',
    'deepseek-chat',
    '你是配送路线微调助手。你会基于规则算法给出的顺序、地址聚类和人工历史偏好，输出一个保持订单集合完全一致的更合理顺序。只允许做轻量调整，优先减少折返、聚合同小区同楼栋订单，并给出一句简短中文原因说明。返回 JSON：{"reasonSummary":"...","orderIds":[...]}。',
    20.00,
    b'0',
    'CNY',
    '',
    '',
    '',
    'system'
) ON DUPLICATE KEY UPDATE id = id;

CREATE TABLE dispatch_ai_job_logs (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trigger_source VARCHAR(32) NOT NULL COMMENT 'AUTO_SCHEDULE / MANUAL_RUN / BALANCE_REFRESH',
    serve_date DATE NULL,
    meal_period VARCHAR(16) NULL,
    area_code VARCHAR(64) NULL,
    suggestion_id BIGINT NULL,
    status VARCHAR(16) NOT NULL COMMENT 'SUCCESS / FAILED / SKIPPED',
    suggestion_source VARCHAR(32) NULL,
    reason_summary VARCHAR(255) NOT NULL DEFAULT '',
    message VARCHAR(255) NOT NULL DEFAULT '',
    metadata_json TEXT NULL,
    executed_by VARCHAR(64) NOT NULL DEFAULT 'system',
    started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP NULL,
    INDEX idx_dispatch_ai_job_logs_started_at (started_at),
    INDEX idx_dispatch_ai_job_logs_scope (serve_date, meal_period, area_code),
    INDEX idx_dispatch_ai_job_logs_trigger (trigger_source, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
